services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"
      - "38899:38899/udp"
      - "38900:38900/udp"
    restart: unless-stopped
    privileged: true

volumes:
  homeassistant_config:
